name: 刷步数

on:
  schedule:
    - cron: '27 1,4,6,8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5   # <--- 加上这一行！代表最多跑5分钟，超时自动失败
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4

      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y

      - name: 初始化Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 开始
        env:
          CONFIG: ${{ secrets.CONFIG }}
          AES_KEY: ${{ secrets.AES_KEY }}
        run: |
          pip3 install -r requirements.txt
          python3 main.py

      - name: persist tokens
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update tokens"
          git push
